server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehicles
          uri: lb://ms-vehicles
          predicates:
            - Path=/vehicles/**
        - id: ms-repair-list
          uri: lb://ms-repair-list
          predicates:
            - Path=/repair-list/**
        - id: ms-repairs
          uri: lb://ms-repairs
          predicates:
            - Path=/repairs/**
        - id: ms-reports
          uri: lb://ms-reports
          predicates:
            - Path=/reports/**