apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-repair-list-deployment
  labels:
    app: ms-repair-list-deployment
spec:
  selector:
    matchLabels:
      app: ms-repair-list-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-repair-list-deployment
    spec:
      containers:
        - name: ms-repair-list
          image: josellancamil/ms-repair-list
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIRLIST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIRLIST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPAIRLIST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPAIRLIST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPAIRLIST